### ISSUE TITLE
Autobahn has an error running on Android phones

### ISSUE THREAD

**Issue by ownbylichaobao** [crossbario/autobahn-js#419] opened 2019-04-28 02:53 UTC
Hi, when I use autobahnjs in uni-app, I found that wamp works fine in the browser (Google), but when I package uni-app into apk and install it on my phone, I get an error.

![image](https://user-images.githubusercontent.com/37684963/56857494-eb9b0600-69a0-11e9-9154-8d9328c8b120.png)

Then I found out that the autobahn will determine if it is a node environment before starting, the code here is normal in the web broswer,but  there will be errors in the app.
This code is in lib-> transport->websocket.js

![image](https://user-images.githubusercontent.com/37684963/56857569-cfe42f80-69a1-11e9-8a12-13a896c91e4e.png)

The code that runs on the phone **global.process.version** will have an undefind error,so I change it to this 

![image](https://user-images.githubusercontent.com/37684963/56857599-2c474f00-69a2-11e9-83f3-950fc720ce5a.png)

And change the code in else to the following

![image](https://user-images.githubusercontent.com/37684963/56857617-86481480-69a2-11e9-99d6-43aba19e8a12.png)

broswerTest() is the anonymous function in the else branch.
Then it works fine on the phone.

**Comment by oberstet** [comment] 2019-04-28 05:23
The problem is: there are many environments in which AutobahnJS runs (in principle), so the main thing here is how to detect the environment _reliably_. Once we have detected, we can do the right things inside the library.

Do you have _code_ that detects your phone env (and only that!)?

**Comment by ownbylichaobao** [comment] 2019-04-28 05:56
@oberstet change it to false can resolve my problem, I only use it in this case, and if  I don't do that ,the   “cannot read  property "node" of undefined" error will occur,
 anyway thank you!

**Comment by oberstet** [comment] 2019-04-28 06:09
sure, I get that. but we need dynamic code to detect it. I can't test it, so we will close this issue

**Closed by oberstet** 2019-04-28 06:09 UTC

**Comment by ownbylichaobao** [comment] 2019-04-28 06:11
ok thanks

**Comment by ownbylichaobao** [comment] 2019-04-28 06:12
ok thinks
