### ISSUE TITLE
try catch (e) -> log.debug "hides away" client handler code exceptions

### ISSUE THREAD

**Issue by bachi76** [crossbario/autobahn-js#224] opened 2016-08-12 19:42 UTC
The Connection class silently "consumes" any exceptions in a passed handler code. This is unexpected and hard to debug.

```
self._session.onjoin = function (details) {
    if (self.onopen) {
        try {
            self.onopen(self._session, details);
        } catch (e) {
            log.debug("Exception raised from app code while firing Connection.onopen()", e);
        }
    }
};
```

Suggest to change it to _log.error()_ or similar.

**Comment by oberstet** [comment] 2016-09-14 07:36
Yep, agreed. `log.error` would be better.

**Comment by pjanik** [comment] 2016-10-22 23:33
+1

The client code exceptions are either hidden and impossible to debug or I need to turn on autobahn debugging (AUTOBAHN_DEBUG flag), but then I'm flooded with lots of other messages.

Why are those exception being caught at all? If my handler is broken, I'd expect that my app breaks and to see that in console. Why is some external library trying to catch and "handle" it? I'm not even using autobahn directly (another lib is using it).

**Comment by oberstet** [comment] 2016-11-04 17:12
@pjanik exceptions raised from async code are tricky .. eg for a starter: https://github.com/cujojs/when/blob/master/docs/api.md#debugging-promises

**Comment by pjanik** [comment] 2016-11-04 17:54
@oberstet, I know. But let me ask how does [this piece of code](https://github.com/crossbario/autobahn-js/blob/c4d3e5addca12ccc9b5903772494de3b0299f703/package/lib/session.js#L514-L518) relate to the mentioned article?

IMHO it's just very opinionated decision to swallow **my** exception and optionally log it (only if DEBUG flag is turned on). I think it's is really strange pattern.

If I comment out this try-catch block, application crashes when my code throws an exception and I can see see the call stack. For me this is definitely expected behaviour. I should handle my exceptions and if not - crash. It's pretty weird that external library wraps my code in big try-catch block and don't let my app crash. If I wanted to do it, I would just add similar try-catch block inside my handler.

**Comment by samson84** [comment] 2017-02-08 15:34
+1, its even hides the assertion errors :(.

**Comment by samson84** [comment] 2017-02-10 16:29
Hi, I would like to improve this part of the code (my motivation: I want to write a nice unit tests for my application with usage of Mocha + assert libs, and also useful in my application's WAMP API wrapper):
 
 @oberstet what do you think is it fit into the architecture? Is it worth my time to contribute to this code that way?
 
  1. change the log.debug() to log.error() in a case of onopen and onclose handler's catch part.
  2. add an option to the Connection object somthing like throw_user_application_error: boolean, with default value false. If this option is set to true, the catch blocks in onopen and onclsoe rethrows the errors, causing crashing the app on client side.
  3. update a documentation
 
 **Reasoning**
  - The throw_user_application_error option looks like similar than use_es6_promises, effects the whole autobahn API behavior, fit among the Connection class's options.
  - Onclose and onopen part of the error handling will be documented, the user can control what he/she wants. (works his/her application in a nuclear power plant in any case or throws error if it needs to throws it)
  - The modification backward compatible, not hurts the legacy behavior.
  - I checked the structure of connection.js and session.js: the onleave handler call the user defined onclose handler after the async operations and WAMP messages (onleave call - ABORT, GOODBYE) are handled in the underlaying layers. If an exception aborts the client's code at this point, we lost the reconnection handling which is expected in a case of fatal error (especially if it is documented).
  - In a case of onopen, an onjoin handler calls the user defined function after the async operations and WAMP messages (onjoin - WELCOME) are handled on the underlaying layers, so the connection is built up a normal way. When a user code throws an Error, it crash the whole app, including the TCP handler. The WAMP router detects this event, and recognize the connection lost at TCP level, and close it unclean way. This is the expected behavior in a case of client app crash (`wasClean=False, code=1006, reason="connection was closed uncleanly (peer dropped the TCP connection without previous WebSocket closing handshake)"`)
  - both behaviors will be documented at the throwUserApplicationError option, a user will be well informed about the way of working of the API.
  - the onclose and onopen callbacks, are executing after the async operations, not returns Promises, a simple user application code is executed here. The given exceptions here aren't needed to handle asynchronously "after", this part is also not encompass any async operation, so it is safe to crash here.

Thank you for your answer.

**Comment by oberstet** [comment] 2017-02-16 17:06
@samson84 @pjanik Ok, you've convinced me - we need to improve the behavior here. It's clearly unexpected and not flexible enough.

What we do in AutobahnPython is this: https://github.com/crossbario/autobahn-python/blob/master/autobahn/wamp/protocol.py#L390

That is, have a "user error handler" with default behavior logging a stack trace at error log level. This handler is called whenever a user event or call handler throws. A user can override the "user error handler", and eg rethrow the same exception, a modifed or different one or do sth else.

With AB JS, the user error handler could be configured as an option on the Connection object.

What do you think?

**Comment by samson84** [comment] 2017-02-16 22:56
Hi, 
it is sounds good. You have right, it is better if the whole behavior can be redefined by the user than using an arbitrary flag.

If I understand correctly, one Connection class level error handler handle all the exceptions from user code, e.g: onopen, onclose,  error in remote procedure, error in subscriber callback. 

**Is it possible somehow to make a difference between errors thrown in a different callback?**

For Example a TypeError can be thrown in an onopen or in a remote procedure callback. In the first case, I just want to simple log the case, but in the second case I probably want to notify the caller with some custom "internal server error" message.

 * Perhaps worth to define different user error handlers for each cases (just a type of error handling, or can be different by each registration for example). On the other hand, better if the different implementations (python, js) has a similar interface and behavior. 
 * A solution can be one class level user error handler **and** user error handlers for each cases also. If the error handler for the specific case is not exist, the class level error handler can be used, if it is not exists, a default behavior, an error level logging is executed.
 * Another possible solution to give an extra parameter to the class level error handler, which somehow defines the source of the error.

**Comment by oberstet** [comment] 2017-02-17 14:47
Regarding differentiating the source of the error (onopen, onclose, "on event", "on call", "on progress" handlers), we could use different exception types, but always fire the same "on user error" optional callable on the connection object.

Advantage would be: this is approach stays within the design as currently in AutobahnPython (where above differentation is missing, but could be added too of course).

**Comment by samson84** [comment] 2017-02-17 15:15
I agree, it is important to make a coherent interface.

**Comment by samson84** [comment] 2017-02-17 15:17
Can I contribute in this work?

**Comment by oberstet** [comment] 2017-02-17 15:23
@samson84 Sure, would be cool! A PR is definitely welcome =)

Maybe it is also worth considering having two configurable callbacks for such errors:

* `on_user_error` (stemming from onopen, onclose, ..)
* `on_internal_error`

The latter being used at lines like this https://github.com/crossbario/autobahn-js/blob/master/lib/connection.js#L195

**Comment by samson84** [comment] 2017-02-17 16:41
ok, 
so this on_internal_errors for those try .. catch blocks, that are not really bind to a user defined callback.

**Comment by oberstet** [comment] 2017-02-17 18:01
yep, that's the idea. the default implementation of `on_internal_error` would just log at error level probably. but a user might wish for different behavior for this errors, as those are really bugs in autobahn - and we should fix those;)

**Comment by samson84** [comment] 2017-03-17 23:30
hi, I have started to work on that just now, but I am doing.

**Comment by rogersp** [comment] 2017-05-02 22:09
Any progress on this issue? Errors thrown in subscription handlers are being swallowed rather silently as well: https://github.com/crossbario/autobahn-js/blob/master/lib/session.js#L514

**Comment by samson84** [comment] 2017-08-27 21:57
Created a PR for that, sry for the waiting.

**Comment by aberres** [comment] 2017-11-23 08:20
FWIW I just stumbled upon another `log.debug` when an exception is thrown in a subscription event handler.

Same problem there as described above.

**Comment by aberres** [comment] 2017-11-23 08:22
Ah, I see this is handled by the merged PR as well 👍

**Comment by oberstet** [comment] 2017-11-23 19:35
yeah, actually this issue here is fixed via https://github.com/crossbario/autobahn-js/pull/318

**Closed by oberstet** 2017-11-23 19:35 UTC
Labels: enhancement, needs-discussion
