### ISSUE TITLE
Publish autobahn-js-built to npm

### ISSUE THREAD

**Issue by manas-chaudhari** [crossbario/autobahn-js#306] opened 2017-06-01 03:18 UTC
I get this error when creating production build.
```
Failed to compile.

static/js/main.955798b7.js from UglifyJs
Unexpected token: name (Simple) [./~/cbor/lib/simple.js:9,0][static/js/main.955798b7.js:10295,6]

error Command failed with exit code 1.
```

Content at `static/js/main.955798b7.js:10295,6`
```
class Simple {
      ^
```

Instructions to reproduce:
```
create-react-app test
cd test
yarn add autobahn

# In src/App.js, append the following line: 
import autobahn from 'autobahn';

yarn run build
```

I am very new to this. Here are my thoughts:
I think the discussion is https://github.com/facebookincubator/create-react-app/issues/984#issuecomment-257105773 is relevant here.  It mentions that ES6 syntax in dependencies is not supported by `create-react-app`. If that's the case, can we transpile before publishing the `autobahn` npm module?

**Comment by adrlen** [comment] 2017-06-07 08:54
Ok so the problem is [hildjj/node-cbor](https://github.com/hildjj/node-cbor/) is ES6 and UglifyJS doesn't support it. It should be transpiled by Babel but I'm not sure when this must be done..

**Comment by adrlen** [comment] 2017-06-16 09:04
@oberstet Do you have any info on this topic ? Thanks for your time.

**Comment by oberstet** [comment] 2017-06-23 08:32
@adrlen Sorry, I don't have info on that and no time to look into this also. Autobahn officially supports 2 ways of use and distribution:

1. browsers: pre-built library from https://github.com/crossbario/autobahn-js-built
2. Node: npm

**Comment by glortho** [comment] 2017-07-19 14:26
We've had so many struggles getting autobahn to work with webpack that we should've stopped trying a long time ago. But we're committed to a predictable, ergonomic strategy for package bundling, versioning, etc. so this is our solution to the latest quagmire:

**webpack.config.js**
```javascript
{
  test: /\.js$/,
  include: /mySrcDir|cbor/,
    use: {
      loader: 'babel-loader',
      ...
}
```

**Comment by offroff** [comment] 2017-08-17 07:02
I manually copied the pre-built library to my create-react-app. That works but it's not a good solution in the long run. Can you publish the pre-built version to the npm registry?

**Comment by adrlen** [comment] 2017-08-23 14:07
Actually, there is already an old pre-build version published on npmjs by a random stranger.
https://www.npmjs.com/package/autobahn-js-built

@oberstet Why isn't this repo published on npm by your team ?

**Comment by oberstet** [comment] 2017-08-23 14:16
@adrlen as we don't have to intro code changes for this (to support yet another JS build thingy), we could push autobahn-js-built to npm of course when doing a release to this repo with low effort, yes.

ok, we probably should given this seems to be of interest to quite some developers, and before people use stuff released by strangers, definitely.

**Comment by oberstet** [comment] 2017-08-23 14:20
we might need some mods to the packge.json in https://github.com/crossbario/autobahn-js-built

maybe a Makefile with a "publish" target that invokes `npm publish`

apart from that, this step of releasing _also_ the browser built version to npm should then be documented in https://github.com/crossbario/autobahn-js/blob/master/doc/release-process.md

**Comment by adrlen** [comment] 2017-08-23 14:27
Might be worthy to be mentioned here too ?

https://github.com/crossbario/autobahn-js#browser-development

Thanks !

**Comment by karser** [comment] 2017-09-13 12:53
autobahn-js-built v0.11.2 doesn't contain ES6:
```
npm install --save autobahn@git://github.com/crossbario/autobahn-js-built.git#v0.11.2
npm install --save-dev @types/autobahn
```

**Comment by adrlen** [comment] 2018-03-16 09:40
Any news about this ?

Thanks again for this great lib !

**Comment by oberstet** [comment] 2018-03-16 15:04
Ok, I've added steps to release the browser build to npm, and pushed v18.3.1 : https://github.com/crossbario/autobahn-js-browser#using-with-npm

**Closed by oberstet** 2018-03-16 15:04 UTC
Labels: enhancement

**Comment by adrlen** [comment] 2018-03-16 17:26
Thanks a lot!
