### ISSUE TITLE
VPN disconnection on Chrome Android

### ISSUE THREAD

**Issue by esso23** [crossbario/autobahn-js#194] opened 2016-05-02 13:29 UTC
When I have an autobahn connection established through VPN on Android Chrome and I disconnect the VPN, the connection.isOpen and session.isOpen still return true. Also when I try to call an RPC it does not throw an exception.
This means I have no way of notifying the user that the connection is broken.
When I try the same on Chrome on Win10 everything works fine and calling an RPC throws an exception.

**Comment by oberstet** [comment] 2016-05-03 05:08
I've had issues with a VPN myself already. That was on a Windows desktop and with some Citrix enterprise VPN gateway, where the WAMP-WebSocket connection couldn't be established at all. I didn't had the time to track down or solve the issue though yet. The issues are likely due to the VPN interfering with WebSocket.

So there are 2 aspects here:

1. how can we make it work?
2. how can we detect that is doesn't work?

In your case, do I understand correctly? The WAMP-WebSocket connection is successful in the first place, but when you later disconnect the VPN, the loss of connectivity isn't detected by Autobahn?

Further questions:

* are you using secure WebSocket? ("wss" URL)
* what VPN software exactly?
* what WAMP router?
* do you have WebSocket automatic ping/pong enabled on your WAMP router?

**Comment by esso23** [comment] 2016-05-03 14:31
> The WAMP-WebSocket connection is successful in the first place, but when you later disconnect the VPN, the loss of connectivity isn't detected by Autobahn?
Yes, exactly. I am implementing a feature into my website which will notify user when the WAMP Router is not reachable.

> are you using secure WebSocket? ("wss" URL)
No.

> what VPN software exactly?
Standard Windows 10 VPN (integrated).

> what WAMP router?
WampSharp

> do you have WebSocket automatic ping/pong enabled on your WAMP router?
Don't know what this is exactly (I don't think WampSharp has this feature) - I have an RPC implemented on a client that is inside the VPN network and I'm periodically calling this RPC to check the connection.

**Comment by oberstet** [comment] 2016-11-15 10:25
This is likely an issue specific to the VPN used - I cannot reproduce, as I have left Windows anyways. Sorry =( Closing ..

**Closed by oberstet** 2016-11-15 10:25 UTC
Labels: needs-investigation
