### ISSUE TITLE
Make connection.open() return a promise

### ISSUE THREAD

**Issue by sametmax** [crossbario/autobahn-js#144] opened 2015-07-02 13:22 UTC
call() returns a promise, but the connection object expect you to register the connection.onopen callback. Not only this makes the API heterogeneous, callbacks are also less flexible than promises and the current implementation prevents us to have several handlers.

This would also emphasis the need to separate the connection failure (promise.reject) and the connection closing which is just an event after the connection has been successful (hence might be a callback or some kind of event handler)

**Comment by oberstet** [comment] 2015-07-02 15:57
yes, this is by design, since `onconnect` can fire multiple times (in case of automatic reconnection). Hence `Connection.open` can't return a promise (which can only be resolved/rejected once)

**Comment by sametmax** [comment] 2015-07-02 16:51
This is not incompatible. You can return a promise and provide an event system for further calls. Or at least provide a way to hook multiple handlers to the callback.

**Comment by oberstet** [comment] 2015-07-02 17:09
@sametmax Do you have proposal for an alternative API? In general, I can follow the thinking that a  homogenous promise-based API might be better .. it's just that it needs to cover reconnection as well.

also: with http://autobahn.ws/js/reference.html#progressive-results, the progress handler is called multiple times.

however: http://autobahn.ws/js/reference.html#connection-options "Using ES6-based promises has certain restrictions. E.g. no progressive call results are supported."

**Comment by sametmax** [comment] 2015-07-02 22:39
I would say something : 

```
connection.open().then(
// first connection is up
).fail(
// first connection failed
)
```

For the day to day use.

Then for advanced usages:

connection.on('event1 event2 event3', function(event, details){
})

To register a callback for when : 

- the connection opens ('open')
- the connection opens for the first time ('start')
- the connection is closed by the developer ('close')
- the connection is closed unexpectedly ('lost')
- the connection closes before even having being able to reach the router ('fail')

This should give control to the developer to manage it's application life cycle, especially dealing with offline mode, manual connection recovery, and initialising isolated component on connection opening.

**Comment by Alex-Nabu** [comment] 2015-08-30 02:43
Am I correct in saying. events such as registering callbacks for 'open', 'close' were removed in favour for onopen = function().. If i'm right I have a right time seeing how it was rational to remove registering callbacks for important events. This would allow to register multiple things if multiple things should happen but the code is registered at different places but maintain readability for the code's logic. Not to mention the decision to  move away from such a standard event based api. If I'm wrong please correct me and consider adding the events to the readme.

**Comment by eddieajau** [comment] 2016-06-20 00:55
Agree with @oberstet and disagree with the proposal. There is no benefit returning a promise because it only returns once, and the real work is always done by listening to the events.

However, what we've done instead is add some RxJS Observable sugar to the onopen and onclose events and that's proving to be far more useful. The reason we went this way is because when the connection drops for any reason, on re-connection you have to re-register procedures and re-subscribe to topics. That is just not possible with promise chains.

**Comment by oberstet** [comment] 2019-04-22 08:35
closing this, as it would be a major new API (needed to be provided in parallel to the existing API so not to break existing apps) - and we never had the resources / concrete proposals / PRs.

fwiw, AutobahnPython these days does indeed provide an observer-based "new API" as in:

* https://autobahn.readthedocs.io/en/latest/wamp/programming.html#application-components

in parallel to the older, subclass/callback based API:

* https://autobahn.readthedocs.io/en/latest/wamp/programming.html#session-lifecycle

**Closed by oberstet** 2019-04-22 08:35 UTC
Labels: needs-design, needs-discussion
