### ISSUE TITLE
Could not create WAMP transport 'websocket':  TypeError: Cannot read property 'node' of undefined from ELECTRON-app

### ISSUE THREAD

**Issue by rbrother** [crossbario/autobahn-js#454] opened 2019-07-18 10:33 UTC
We are using non-minified Autobahn 19.7.2 from our packaged electron-applications chromium browser-process. When opening autobahn connection, we get exception:

autobahn.js:5363 could not create WAMP transport 'websocket':  TypeError: Cannot read property 'node' of undefined
    at Factory.create (autobahn.js:4860)
    at Connection._create_transport (autobahn.js:512)
    at retry (autobahn.js:649)
    at Connection.open (autobahn.js:778)
    at CreateAutoBahnConnection (deviceapi.js:8)
    at posti_kioski_gui.devices.open_connection (app.js:4428)

This exception happens in test that tries to detect NODE vs. browser environment:

   // Test below used to be via the 'window' object in the browser.
   // This fails when running in a Web worker.
   //
   // running in Node.js
   //
   if (global.process && global.process.versions.node
       && !global.process.versions.hasOwnProperty('electron') && !global.process.__nwjs) {

We can work-around the problem in our case by replacing the if-condition with if (false) { ... (since the chromium of electron is the "running in the browser" case and needs to go to the else-branch.

The exception is thrown specifically by global.process.versions.node since in this environment global.process.versions is null. Hence for a better fix we recommend adding null-check to the condition:

   if (global.process && global.process.versions && global.process.versions.node
       && !global.process.versions.hasOwnProperty('electron') && !global.process.__nwjs) {

**Comment by oberstet** [comment] 2019-07-18 11:43
duplicate of https://github.com/crossbario/autobahn-js/issues/367

**Closed by oberstet** 2019-07-18 11:43 UTC
