### ISSUE TITLE
Callee documentation

### ISSUE THREAD

**Issue by oberstet** [crossbario/autobahn-js#167] opened 2015-10-27 23:56 UTC
we might lack docs that mention and describe that callee's can return promises .. hence work async

eg https://github.com/crossbario/autobahn-js/pull/165#issue-113461864

maybe we even have an example somewhere? crossbarexamples? the "slow square" stuff comes to mind .. not sure if there is a JS version though

**Comment by goeddea** [comment] 2016-02-13 17:24
added a section in the API reference describing this (also: duplicate of #172)

**Closed by goeddea** 2016-02-13 17:24 UTC
Labels: docs
