### ISSUE TITLE
Missing depandencies in package.json

### ISSUE THREAD

**Issue by konsultaner** [crossbario/autobahn-js#205] opened 2016-05-20 11:36 UTC
I use autobahn in a browserify projekt. installing autobahn with npm install does not include

    utf-8-validate
    bufferutil

they should be part of the depandencies list. To fix this I have to manually add them with

    npm install utf-8-validate
    npm install bufferutil

**Comment by davidwdan** [comment] 2016-05-20 13:14
@konsultaner this is a duplicate of https://github.com/crossbario/autobahn-js/issues/196

Those packages are dependents of `ws` which is not need in the browser version.

**Comment by konsultaner** [comment] 2016-05-20 17:05
I use browserify to organize my code. If you include the package index.js an error occurs. So the name of the issue my be called: Make it compatible to browserify. You could include a npm install script that installs those packages.

**Comment by gajanak** [comment] 2016-05-28 12:15
It would be nice if autobahn npm release should not depend to bufferutils.
Currently: "bufferutil": ">= 1.2.1" 

Bufferutil authors give the advice:

> As the module consists of binary components, it should be used an optionalDependency so when installation fails, it doesn't halt the installation of your module. There are fallback files available in this repository. See fallback.js for the suggest fallback implementation if installation fails. 

ws manage missing this dep by its own fallback. 

best solution would be to minimize required dependencies .... 
someone use it for browser based apps ... without nodejs.

**Comment by oberstet** [comment] 2016-05-31 08:27
we already use browserify to build the library in the browser version. just use that

**Closed by oberstet** 2016-05-31 08:27 UTC
